import os
import re
import sys
sys.path.append("./scripts")

from hecatomb_helpers import *

configfile: "config.yaml"

# Hecatomb DB paths
DBDIR = config["Paths"]["Databases"]
CONPATH = os.path.join(DBDIR, "contaminants")

# Data paths
READDIR = config["Paths"]["Reads"]

# Rename input files if there are any to rename
rename_files(config)

# Pull sample names from the renamed R1 files in /data/renamed/ and store in a list
sampleNameList = []
read1FileList = glob.glob(READDIR + "/renamed/*_R1.fastq.gz")

for read1FileName in read1FileList:
	read1FileName = os.path.basename(read1FileName)
	sampleName = re.sub("_R1.fastq.gz", "", read1FileName)
	
	if not sampleName in sampleNameList:
		sampleNameList.append(sampleName)

SAMPLES, = sampleNameList

PATTERN_R1 = '{sample}_R1'
PATTERN_R2 = '{sample}_R2'

# Rules 

rule all:
	input:
		# step 1 output for now, will update later
		expand("QC/step_1/{sample}.s1.stats", sample = SAMPLES),
		
rule clumpify:
	input:
		r1 = os.path.join(READDIR + "/renamed/", PATTERN_R1 + ".fastq.gz"),
		r2 = os.path.join(READDIR + "/renamed/", PATTERN_R2 + ".fastq.gz")
	output:
		r1 = os.path.join("clumped", PATTERN_R1 + ".clumped.fastq.gz"),
		r2 = os.path.join("clumped", PATTERN_R2 + ".clumped.fastq.gz")
	shell:
		"""
		module load bbtools
		clumpify.sh \
			in={input.r1} \
			in2={input.r2} \
			out={output.r1} \
			out2={output.r2} \
			reorder=a
			ow=t
		""" 

rule remove_leftmost_primerB:
        input:
                r1 = os.path.join("clumped", PATTERN_R1 + ".clumped.fastq.gz"),
                r2 = os.path.join("clumped", PATTERN_R2 + ".clumped.fastq.gz"),
                primers = os.path.join(CONPATH, "primerB.fa")
        output:
                r1 = os.path.join("QC", "step_1", PATTERN_R1 + ".s1.out.fastq"),
                r2 = os.path.join("QC", "step_1", PATTERN_R2 + ".s1.out.fastq"),
                stats = "QC/step_1/{sample}.s1.stats"
        shell:
                """
                module load bbtools
                bbduk.sh \
                        in={input.r1} \
                        in2={input.r2} \
                        ref={input.primers} \
                        out={output.r1} \
                        out2={output.r2} \
                        stats={output.stats} \
                        k=16 hdist=1 mink=11 ktrim=l restrictleft=20 \
                        removeifeitherbad=f \
                        trimpolya=10 ordered=t rcomp=f ow=t
                """
