---
Paths:
  # The database directory is where to save the databases. We will automatically install them if they are not available
  Databases: "databases"
  Reads: test_data/fastq
DatabaseFiles:
  # These are our predefined databases that we screen against, but you may want to replace host with e.g. mouse
  bacteria: bac_uniquespecies_giant.masked_Ns_removed.fasta
  host: human_virus_masked.fasta
  contaminants: vector_contaminants.fa.gz
