# Location of primer sequence(s)
primer: /mnt/data1/databases/contaminants/primerB.fa

# Location of readthrough primer + adapter
primer_ad: /mnt/data1/databases/contaminants/rc_primerB_ad6.fa

# Location of adapters
adapt: /mnt/data1/databases/contaminants/nebnext_adapters.fa

# Location of vector contaminant database
vec: /mnt/data1/databases/contaminants/vector_contaminats.fa.gz

# Location of masked host database
host_masked: /mnt/data1/databases/mouse_masked/

# QC Phred cut-off
qc: 20

# Bacterial genome reference database
bac: /mnt/data1/databases/masked_dbs/genome-collection-combos/reformated/bac_giant/unique_species 

# Ram usage
ram: 128g

# Max substitutions for dereplication
subs: 4
